# Generated by Django 5.0.3 on 2024-03-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='goals',
            new_name='total_points',
        ),
    ]
