# Generated by Django 5.0.3 on 2024-03-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0002_rename_goals_player_total_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_points',
            new_name='points_per_game',
        ),
    ]
